---
- name: Configure timezone
  file:
    src: /usr/share/zoneinfo/{{timezone}}
    dest: /etc/localtime
    state: link
    force: yes

- name: Copy SSH keys
  copy:
    src: "{{item}}"
    dest: /home/vagrant/.ssh
    owner: vagrant
    group: vagrant
    mode: '0600'
  with_fileglob: "{{vagrant_ssh_keys_dir}}/id_*"

- name: Create utils folder if it doesn't exist
  file:
    path: /home/vagrant/utils
    state: directory
    owner: vagrant
    group: vagrant
    mode: '0755'

- name: Copy utils' contents
  copy:
    src: "{{item}}"
    dest: /home/vagrant/utils/
    owner: vagrant
    group: vagrant
    mode: '0755'
  with_fileglob: "{{vagrant_utils_dir}}/*"