name: grafana
services:
   grf:
     image: grafana/grafana-enterprise
     container_name: grafana
     network_mode: "host"
     restart: unless-stopped
     volumes:
      - grafana_vol:/var/lib/grafana
     extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
   grafana_vol:
    driver_opts:
     type: none
     device: /var/lib/docker/volumes/grafana_grafana_vol/_data
     o: bind