---
- name: Add repository
  yum_repository:
    name: code
    description: Visual Studio Code
    baseurl: https://packages.microsoft.com/yumrepos/vscode
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc

- name: Install or upgrade Visual Studio Code
  yum:
    name: code
    state: latest