---
- name: Download Prometheus
  get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v2.52.0/prometheus-2.52.0.linux-amd64.tar.gz"
    dest: "/tmp/prometheus-2.52.0.linux-amd64.tar.gz"
    mode: '0440'

- name: Create /opt/prometheus directory if it doesn't exist
  file:
    path: /opt/prometheus
    state: directory


- name: Extract Prometheus tarball
  unarchive:
    src: "/tmp/prometheus-2.52.0.linux-amd64.tar.gz"
    dest: "/opt/prometheus"
    remote_src: yes

- name: Move Prometheus to its directory
  command: mv /opt/prometheus/prometheus-2.52.0.linux-amd64 /opt/prometheus/prometheus

- name: Create a systemd service file for Prometheus
  copy:
    dest: /etc/systemd/system/prometheus.service
    content: |
      [Unit]
      Description=Prometheus
      After=network.target
      [Service]
      User=root
      ExecStart=/opt/prometheus/prometheus/prometheus --config.file=/opt/prometheus/prometheus/prometheus.yml
      [Install]
      WantedBy=default.target

- name: Reload systemd to recognize Prometheus service
  systemd:
    daemon_reload: yes

- name: Enable Prometheus service to start on boot
  systemd:
    name: prometheus
    enabled: yes

- name: Start Prometheus service
  systemd:
    name: prometheus
    state: started
