---
- hosts: all
  become: yes
  roles:
    - test
    - vagrant
    - developer # Includes basic Git configuration
    - { role: ghcli, when: install_ghcli|bool }
#    - docker
#    - nodejs
    - x11
#    - vscode
#    - postman
