---
- hosts: all
  become: yes
  roles:
#    - test # Simple debug test that prints "Hello-World" and shows that Ansible is working
    - vagrant
    - developer # Includes basic Git configuration
    - zsh
    - zsh-omz
    - { role: ghcli, when: install_ghcli|bool }
    - { role: docker, when: install_docker|bool }
    - { role: nodejs, when: install_nodejs|bool }
#    - x11
    - { role: pgadmin, when: install_pgadmin|bool }
    - { role: vscode, when: install_vscode|bool }
    - { role: postman, when: install_postman|bool }
    - { role: prometheus, when: install_prometheus|bool }
