---
- hosts: all
  become: yes
  roles:
    - test
    - vagrant
    - developer # Includes basic Git configuration
    - zsh
    - zsh-omz
    - { role: ghcli, when: install_ghcli|bool }
    - { role: docker, when: install_docker|bool }
#    - nodejs
    - x11
    - { role: pgadmin, when: install_pgadmin|bool }
#    - vscode
#    - postman
