---
- hosts: all
  become: yes
  roles:
    - test
    - vagrant
    - developer # Includes basic Git configuration
    - zsh
    - zsh-omz
    - { role: ghcli, when: install_ghcli|bool }
    - { role: docker, when: install_docker|bool }
    - { role: nodejs, when: install_nodejs|bool }
    - x11
    - { role: pgadmin, when: install_pgadmin|bool }
    - { role: vscode, when: install_vscode|bool }
    - { role: postman, when: install_postman|bool }
